In [2]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity

In [5]:
cosine_similarity([[3,1]], [[6,2]])

array([[1.]])

In [6]:
cosine_distances([[3,1]], [[6,2]])

array([[1.11022302e-16]])

array([[1.11022302e-16]]) is vey close to zero

In [7]:
cosine_similarity([[3,1]], [[3,2]])

array([[0.96476382]])

In [8]:
cosine_distances([[3,1]], [[3,2]])

array([[0.03523618]])

In [25]:
import pandas as pd

df = pd.read_csv("document.csv")
df = df.set_index('doc')

In [26]:
df.head()

      iPhone  galaxy
doc
doc1       3       1
doc2       2       0
doc3       1       3
doc4       1       2

In [27]:
df.loc["doc1" : "doc1"]

      iPhone  galaxy
doc
doc1       3       1

In [ ]:
cosine_similarity(df.loc['doc1': 'doc1'], df.loc['doc2':'doc2'])

array([[0.9486833]])

### very similar both are apple documents

In [29]:
cosine_distances(df.loc['doc1': 'doc1'], df.loc['doc2':'doc2'])

array([[0.0513167]])

In [30]:
cosine_similarity(df.loc['doc1': 'doc1'], df.loc['doc3':'doc3'])

array([[0.6]])

### Not that similar

In [31]:
cosine_similarity(df.loc['doc1': 'doc1'], df.loc['doc4':'doc4'])

array([[0.70710678]])

### consider as similar

In [32]:
cosine_similarity(df.loc['doc3': 'doc3'], df.loc['doc4':'doc4'])

array([[0.98994949]])

### very similar